root: true
env:
  browser: true
  es2021: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - "@typescript-eslint"
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
rules:
  react/prop-types: "off"
