import "@fontsource/noto-sans-jp"
import "@fontsource/noto-sans-jp/300.css"
import "@fontsource/noto-sans-jp/700.css"
import "@fontsource/roboto"
import "@fontsource/roboto/300.css"
import "@fontsource/roboto/700.css"
